// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo_eRlBIFl6fAGvZGSP5RqP8aTD6JWBU8',
    appId: '1:107548260538:web:72163a28464bdddaa2aa83',
    messagingSenderId: '107548260538',
    projectId: 'dalel-9f202',
    authDomain: 'dalel-9f202.firebaseapp.com',
    storageBucket: 'dalel-9f202.appspot.com',
    measurementId: 'G-KL6ZB1FP1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQU0jkr4yfbIxRF3ar5PTS--rhEkSrmbs',
    appId: '1:107548260538:android:f8fc4095e1d64e5ba2aa83',
    messagingSenderId: '107548260538',
    projectId: 'dalel-9f202',
    storageBucket: 'dalel-9f202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjNtd918rBiJ7jTMwGDCtFYZkNvpdYshc',
    appId: '1:107548260538:ios:c76dfb3e66c1f992a2aa83',
    messagingSenderId: '107548260538',
    projectId: 'dalel-9f202',
    storageBucket: 'dalel-9f202.appspot.com',
    iosBundleId: 'com.example.dalil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjNtd918rBiJ7jTMwGDCtFYZkNvpdYshc',
    appId: '1:107548260538:ios:c76dfb3e66c1f992a2aa83',
    messagingSenderId: '107548260538',
    projectId: 'dalel-9f202',
    storageBucket: 'dalel-9f202.appspot.com',
    iosBundleId: 'com.example.dalil',
  );
}
